plotter:
  b: 360
  pins: {    
    leftDirPin: 16, leftEnable: 18, leftStpPin: 22, 
    penPin: 12, 
    rightDirPin: 32,rightEnable: 36, rightStpPin: 38    
    }
  spoolDiameter: 79
  stepsPerRotation: 2048
